services:
  - type: web
    name: nexchat-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 server:app
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://admin:lMbldplhPX9cJMfI@ac-i59faml-shard-00-00.so0lysv.mongodb.net/nexchat_v2?retryWrites=true&w=majority
      - key: SECRET_KEY
        value: 8f2a99c1b3d7e5f6a4c2b9d8e7f1a3c5b7d9e2f4a6c8b0d1e3f5a7c9b1d3e5f7
      - key: PORT
        value: 5000